import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,blank,escapeHtml,documentDefinition,example} from '../src/model.js';
import {safeProperties,attribution} from '../src/telemetry-core.js';
test('restored drafts reject malformed records and bound content',()=>{const d=normalize({name:'a'.repeat(400),experience:[null,42,{title:'Real',description:100}],template:'<script>',accent:'url(evil)',language:'bad'});assert.equal(d.name.length,100);assert.equal(d.experience.length,1);assert.equal(d.experience[0].title,'Real');assert.equal(d.experience[0].description,'');assert.equal(d.template,'modern');assert.equal(d.accent,'#234bff');assert.deepEqual(normalize(null),blank())});
test('preview escapes untrusted HTML',()=>assert.equal(escapeHtml('<img src=x onerror="x">'), '&lt;img src=x onerror=&quot;x&quot;&gt;'));
test('PDF omits empty sections and preserves Macedonian content',()=>{const d=documentDefinition({...blank(),name:'Ѓорѓи Ќосев',summary:'Љубов, Њ, Џ, Ѕ'});assert.ok(JSON.stringify(d.content).includes('Ѓорѓи Ќосев'));assert.ok(!JSON.stringify(d.content).includes('РАБОТНО ИСКУСТВО'));const en=documentDefinition({...blank(),...example,language:'en'});assert.ok(JSON.stringify(en.content).includes('WORK EXPERIENCE'));assert.ok(JSON.stringify(en.content).includes('Ана Стојановска'))});
test('analytics strips all personal and arbitrary properties',()=>{assert.deepEqual(safeProperties({name:'Private',email:'private@example.com',step:3,template:'classic',message:'Secret CV',url:'https://example.com?email=x'}),{step:3,template:'classic'});assert.deepEqual(safeProperties({step:99,template:'evil'}),{})});
test('marketing attribution cannot leak arbitrary URLs or campaign text',()=>{assert.deepEqual(attribution('https://cv.test/?utm_source=google&utm_campaign=mk-search-cv',''),{channel:'google',campaign:'mk-search-cv'});assert.deepEqual(attribution('https://cv.test/?utm_source=private-email&utm_campaign=secret','https://some-company.test/private/path?email=secret'),{channel:'referral',campaign:'none'})});
