import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {verifySignature,handlePayments,hash,claimPayment,finishPayment} from '../worker/payments.js';
import {handleAPI} from '../worker/index.js';
function setup(){const db=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(`drizzle/${file}`,'utf8'));return{db,env:{PAYMENTS_ENABLED:'test',STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'whsec_fake',AI_ENABLED:'true',DEEPSEEK_API_KEY:'fake',AI_MAX_REVIEWS:'10',DB:{prepare:sql=>({bind:(...args)=>({first:async()=>db.prepare(sql).get(...args)})})}}}}
const req=(path,method='GET',cookie)=>new Request(`https://cv.example/api/payments/${path}`,{method,headers:{Origin:'https://cv.example',...(cookie?{Cookie:cookie}:{})}});
async function sign(raw,time=Math.floor(Date.now()/1000)){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('whsec_fake'),{name:'HMAC',hash:'SHA-256'},false,['sign']);return `t=${time},v1=${Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${time}.${raw}`))).toString('hex')}`}
test('webhook rejects tampering and stale signatures',async()=>{const raw='{"test":true}',signature=await sign(raw);assert.equal(await verifySignature(raw,signature,'whsec_fake'),true);assert.equal(await verifySignature(raw+' ',signature,'whsec_fake'),false);assert.equal(await verifySignature(raw,await sign(raw,1),'whsec_fake'),false)});
test('payments are disabled by default and cannot accept live keys',async()=>{assert.equal((await handlePayments(req('checkout','POST'),{})).status,503);assert.equal((await handlePayments(req('checkout','POST'),{PAYMENTS_ENABLED:'test',STRIPE_SECRET_KEY:'sk_live_example',STRIPE_WEBHOOK_SECRET:'test',DB:{}})).status,503)});
test('checkout fixes price, uses secure cookie and never sends CV content',async()=>{const {db,env}=setup();let call;const response=await handlePayments(req('checkout','POST'),env,async(url,options)=>{call={url,options};return Response.json({id:'cs_test_a',url:'https://checkout.stripe.com/c/pay/test_a'})});assert.equal(response.status,200);assert.match(response.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Lax/);assert.equal(call.options.body.get('line_items[0][price_data][unit_amount]'),'1000');assert.equal(call.options.body.get('line_items[0][price_data][currency]'),'nok');assert.equal(call.options.body.get('mode'),'payment');assert.equal(db.prepare('SELECT count(*) n FROM payments').get().n,1);assert.equal(db.prepare('SELECT count(*) n FROM ai_budget').get().n,0);db.close()});
test('signed paid webhook unlocks one use, replay cannot restore used purchase',async()=>{const {db,env}=setup(),token='a'.repeat(64),owner=await hash(token);db.prepare("INSERT INTO payments VALUES (?,?,?,NULL,'pending')").run('order',owner,'cs_test_a');const session={id:'cs_test_a',client_reference_id:'order',mode:'payment',payment_status:'paid',livemode:false,amount_total:1000,currency:'nok',payment_intent:'pi_test_a'};const webhook=async object=>{const raw=JSON.stringify({type:'checkout.session.completed',data:{object}});return handlePayments(new Request('https://cv.example/api/payments/webhook',{method:'POST',headers:{'Stripe-Signature':await sign(raw)},body:raw}),env)};await webhook({...session,amount_total:1});assert.equal(db.prepare('SELECT state FROM payments').get().state,'pending');await webhook(session);const request=req('status','GET',`__Host-cvhapi-payment=${token}`);const claims=await Promise.all([claimPayment(request,env),claimPayment(request,env)]);assert.equal(claims.filter(Boolean).length,1);await finishPayment(env,claims.find(Boolean),true);await webhook(session);assert.equal(db.prepare('SELECT state FROM payments').get().state,'used');db.close()});
test('refund retries use same idempotency key and distinguish pending from succeeded',async()=>{const {db,env}=setup();db.prepare("INSERT INTO payments VALUES ('o','owner','cs','pi','processing')").run();const order=db.prepare('SELECT * FROM payments').get();let keys=[];const transport=async(url,options)=>{keys.push(options.headers['Idempotency-Key']);return Response.json({status:keys.length===1?'pending':'succeeded'})};assert.equal(await finishPayment(env,order,false,transport),'refund_pending');assert.equal(await finishPayment(env,order,false,transport),'refunded');assert.deepEqual(keys,['refund-o','refund-o']);db.close()});
test('paid-mode AI rejects missing entitlement before quota or provider use',async()=>{const {db,env}=setup();let calls=0;const response=await handleAPI(new Request('https://cv.example/api/review',{method:'POST',headers:{Origin:'https://cv.example','Content-Type':'application/json'},body:JSON.stringify({text:'Customer service assistant. '.repeat(10),job:'',language:'en',consent:true})}),env,async()=>{calls++;throw Error()});assert.equal(response.status,402);assert.equal(calls,0);assert.equal(db.prepare('SELECT count(*) n FROM ai_budget').get().n,0);db.close()});
test('quota exhaustion refunds a verified payment without calling AI or resetting quota',async()=>{const {db,env}=setup(),token='b'.repeat(64);db.prepare("INSERT INTO ai_budget VALUES ('pilot',10)").run();db.prepare("INSERT INTO payments VALUES ('o',?,'cs','pi','paid')").run(await hash(token));let calls=[];const response=await handleAPI(new Request('https://cv.example/api/review',{method:'POST',headers:{Origin:'https://cv.example','Content-Type':'application/json',Cookie:`__Host-cvhapi-payment=${token}`},body:JSON.stringify({text:'Customer service assistant. '.repeat(10),job:'',language:'en',consent:true})}),env,async url=>{calls.push(url);return Response.json({status:'succeeded'})});assert.equal(response.status,429);assert.equal((await response.json()).payment,'refunded');assert.deepEqual(calls,['https://api.stripe.com/v1/refunds']);assert.equal(db.prepare('SELECT used FROM ai_budget').get().used,10);db.close()});
