import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {localReview,applySuggestion,validateReview,cvText} from '../src/review-core.js';
import {handleAPI,budgetSQL} from '../worker/index.js';
import {blank} from '../src/model.js';
const source='Customer service assistant. Helped customers choose products and handled checkout transactions. Worked at Example Shop from 2022 to 2024.';
test('unverified API privacy blocks submission before quota and provider access',async()=>{const {db,binding}=database();const env={AI_ENABLED:'true',AI_MAX_REVIEWS:'10',DEEPSEEK_API_KEY:'test',DB:binding};let calls=0;assert.equal((await handleAPI(request(),env,async()=>{calls++})).status,503);assert.deepEqual(await (await handleAPI(new Request('https://cv.example/api/review/status'),env)).json(),{available:false,remaining:null,reason:'privacy_pending'});assert.equal(calls,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM ai_budget').get().n,0);db.close()});
test('status reflects remaining lifetime capacity and fails closed on database errors',async()=>{const {db,binding}=database();const env={AI_PRIVACY_APPROVED:'true',AI_ENABLED:'true',AI_MAX_REVIEWS:'10',DEEPSEEK_API_KEY:'test-only',DB:binding};const status=()=>handleAPI(new Request('https://cv.example/api/review/status'),env);assert.deepEqual(await (await status()).json(),{available:true,remaining:10});db.prepare("INSERT INTO ai_budget VALUES ('pilot',10)").run();assert.deepEqual(await (await status()).json(),{available:false,remaining:0});db.close();assert.equal((await status()).status,503)});
test('false payment setting permits free reviews while unknown modes fail closed',async()=>{const {db,binding}=database();const env={AI_PRIVACY_APPROVED:'true',AI_ENABLED:'true',AI_MAX_REVIEWS:'10',DEEPSEEK_API_KEY:'test-only',DB:binding,PAYMENTS_ENABLED:'false'};let calls=0;const provider=async()=>{calls++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({overview:'Reviewed',strengths:[],questions:[],suggestions:[]})}}]})};assert.equal((await handleAPI(request(),env,provider)).status,200);assert.equal(calls,1);env.PAYMENTS_ENABLED='typo';assert.equal((await handleAPI(request(),env,provider)).status,503);assert.equal(calls,1);db.close()});
const request=(body={},headers={})=>new Request('https://cv.example/api/review',{method:'POST',headers:{Origin:'https://cv.example','Content-Type':'application/json',...headers},body:JSON.stringify({text:source,job:'Customer service and Excel',language:'en',consent:true,...body})});
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('drizzle/0000_sad_george_stacy.sql','utf8'));return{db,binding:{prepare:sql=>({bind:(...args)=>({first:async()=>db.prepare(sql).get(...args)})})}}}
test('review matches whole words and only applies a quoted suggestion',()=>{const result=localReview('Excel and customer service. Test@example.com 2024','Excel sales');assert.deepEqual(result.matched,['excel']);assert.deepEqual(result.missing,['sales']);assert.equal(result.hasEmail,true);assert.throws(()=>applySuggestion(source,{original:'invented',revised:'Other'}));assert.equal(applySuggestion('Original text',{original:'Original text',revised:'Keep $& literally'}),'Keep $& literally');assert.equal(validateReview({overview:'OK',suggestions:[{original:'not in source',revised:'Made up',reason:'x'}]},source).suggestions.length,0);assert.equal(cvText(blank()),'')});
test('AI never calls provider without configuration, consent and same origin',async()=>{let calls=0;const provider=async()=>{calls++;throw Error()};const {db,binding}=database();const env={AI_PRIVACY_APPROVED:'true',AI_ENABLED:'true',AI_MAX_REVIEWS:'10',DEEPSEEK_API_KEY:'test-only',DB:binding};assert.equal((await handleAPI(request(),{},provider)).status,503);assert.equal((await handleAPI(request({consent:false}),env,provider)).status,400);assert.equal((await handleAPI(request({}, {Origin:'https://evil.example'}),env,provider)).status,403);assert.equal((await handleAPI(request({text:'a'.repeat(20001)}),env,provider)).status,400);assert.equal(calls,0);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM ai_budget').get().n,0);db.close()});
test('durable lifetime cap permits ten concurrent reservations and never stores CV data',async()=>{const {db,binding}=database();const results=await Promise.all(Array.from({length:30},()=>binding.prepare(budgetSQL).bind(10).first()));assert.equal(results.filter(Boolean).length,10);assert.deepEqual({...db.prepare('SELECT * FROM ai_budget').get()},{id:'pilot',used:10});db.close()});
test('provider output is validated and quota is enforced before provider call',async()=>{const {db,binding}=database();const env={AI_PRIVACY_APPROVED:'true',AI_ENABLED:'true',AI_MAX_REVIEWS:'1',DEEPSEEK_API_KEY:'test-only',DB:binding};let calls=0;const provider=async(url,options)=>{calls++;assert.equal(url,'https://api.deepseek.com/chat/completions');const body=JSON.parse(options.body);assert.equal(body.model,'deepseek-flash');assert.equal(body.max_tokens,2200);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({overview:'Make the work specific.',strengths:['Dates are clear'],questions:['What did you achieve?'],suggestions:[{original:'Helped customers choose products',revised:'Advised customers on product choices',reason:'Use a precise action verb.'},{original:'Managed 50 people',revised:'Led 50 people',reason:'Unsupported'}]})}}]})};const response=await handleAPI(request(),env,provider);assert.equal(response.status,200);assert.equal((await response.json()).suggestions.length,1);assert.equal((await handleAPI(request(),env,provider)).status,429);assert.equal(calls,1);db.close()});
