import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {build} from 'esbuild';
const bundle=await build({entryPoints:['src/main.js'],bundle:true,write:false,format:'iife',loader:{'.css':'empty'},define:{'import.meta.env.VITE_POSTHOG_KEY':'""','import.meta.env.VITE_POSTHOG_HOST':'"https://eu.i.posthog.com"'},logLevel:'silent'});
test('private CV-only backend explains its scope and prevents unsupported letter submissions',async()=>{
 const dom=boot(),w=dom.window,d=w.document;w.fetch=async()=>({ok:true,json:async()=>({available:true,testMode:'private_cv_only'})});
 d.querySelector('[data-action="example"]').click();d.querySelector('#review-toggle').click();await new Promise(r=>setTimeout(r,0));d.querySelector('#review-from').click();
 assert.match(d.querySelector('#review-ai-privacy').textContent,/private owner test/);assert.match(d.querySelector('#ai-availability').textContent,/CV-only/);assert.equal(d.querySelector('#review-consent').disabled,false);
 d.querySelector('#review-consent').click();await new Promise(r=>setTimeout(r,0));assert.equal(d.querySelector('#review-ai').disabled,false);
 const letter=d.querySelector('#review-letter');letter.value='An optional cover letter';letter.dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('#review-ai').disabled,true);
 letter.value='';letter.dispatchEvent(new w.Event('input'));d.querySelector('#review-consent').click();await new Promise(r=>setTimeout(r,0));assert.equal(d.querySelector('#review-ai').disabled,false);dom.window.close();
});
function boot(saved){const dom=new JSDOM('<div id="app"></div>',{url:'https://cv.test',runScripts:'outside-only'});dom.window.structuredClone=structuredClone;dom.window.HTMLElement.prototype.scrollIntoView=function(options){dom.window.lastScroll={id:this.id,options}};dom.window.matchMedia=()=>({matches:false});dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false};if(saved)dom.window.localStorage.setItem('cekor.cv.v1',saved);dom.window.eval(bundle.outputFiles[0].text);return dom}
test('AI checkout appears only after document preparation and consent, then verified payment unlocks review',async()=>{
 const dom=boot(),w=dom.window,d=w.document;let paid=false,posted=0,configCalls=0;w.AbortSignal=AbortSignal;
 w.fetch=async(url,options)=>{if(url==='/api/review/status')return{ok:true,json:async()=>({available:true})};if(url==='/api/payments/config'){configCalls++;return{ok:true,json:async()=>({enabled:true,test:true})}}if(url==='/api/payments/status')return{ok:true,json:async()=>({state:paid?'paid':'none'})};assert.equal(url,'/api/review');assert.equal(JSON.parse(options.body).consent,true);posted++;return{ok:true,json:async()=>({overview:'Reviewed',suggestions:[]})}};
 d.querySelector('#review-toggle').click();await new Promise(r=>setTimeout(r,0));assert.equal(configCalls,0);assert.equal(d.querySelector('.payment-choice'),null);
 assert.match(d.querySelector('.ai-disclosure').textContent,/DeepSeek/);assert.equal(d.querySelector('.ai-disclosure').open,false);assert.doesNotMatch(d.querySelector('.ai-choice h3').textContent,/DeepSeek/);
 d.querySelector('[data-action="example"]').click();d.querySelector('#review-from').click();assert.equal(configCalls,0);d.querySelector('#review-consent').click();await new Promise(r=>setTimeout(r,0));assert.equal(configCalls,1);assert.match(d.querySelector('[data-buy]').textContent,/€2/);assert.equal(d.querySelector('#review-ai').disabled,true);
 paid=true;d.querySelector('[data-check]').click();await new Promise(r=>setTimeout(r,0));assert.equal(d.querySelector('#review-ai').disabled,false);d.querySelector('#review-ai').click();await new Promise(r=>setTimeout(r,0));assert.equal(posted,1);assert.ok(d.querySelector('.ai-results'));dom.window.close();
});
test('CV flow edits, reorders, deletes, changes template and restores saved draft',()=>{const dom=boot(),w=dom.window,d=w.document;const click=s=>d.querySelector(s).click(),fill=(s,v)=>{const x=d.querySelector(s);x.value=v;x.dispatchEvent(new w.Event('input',{bubbles:true}))};fill('#name','Ѓорѓи Тест');fill('#summary','<img src=x onerror=alert(1)>');assert.equal(d.querySelector('.paper h2').textContent,'Ѓорѓи Тест');assert.equal(d.querySelector('.paper img'),null);click('[data-step="1"]');click('[data-add="experience"]');fill('#experience-0-title','First');click('[data-add="experience"]');fill('#experience-1-title','Second');click('[data-move="experience:1:-1"]');assert.equal(d.querySelector('#experience-0-title').value,'Second');click('[data-remove="experience:0"]');click('#modal-action');assert.equal(d.querySelector('#experience-0-title').value,'First');click('[data-step="4"]');click('input[value="compact"]');assert.ok(d.querySelector('.paper.compact'));const r=d.querySelector('#remember');r.checked=true;r.dispatchEvent(new w.Event('change'));const saved=w.localStorage.getItem('cekor.cv.v1');const restored=boot(saved);assert.equal(restored.window.document.querySelector('#name').value,'Ѓорѓи Тест');restored.window.close();dom.window.close()});
test('export validates name without downloading fictional example; reset removes saved data',()=>{const dom=boot(),d=dom.window.document;d.querySelector('[data-action="export"]').click();assert.equal(d.querySelector('#name').getAttribute('aria-invalid'),'true');assert.ok(!d.querySelector('#modal').open);d.querySelector('[data-action="example"]').click();assert.equal(d.querySelector('#name').value,'Ana Stojanovska');d.querySelector('[data-action="reset"]').click();d.querySelector('#modal-action').click();assert.equal(d.querySelector('#name').value,'');assert.equal(dom.window.localStorage.getItem('cekor.cv.v1'),null);dom.window.close()});
test('application flow validates, preserves text through language switch and blocks stale drafts',()=>{const dom=boot(),w=dom.window,d=w.document;const click=s=>d.querySelector(s).click(),fill=(s,v)=>{const el=d.querySelector(s);el.value=v;el.dispatchEvent(new w.Event('input',{bubbles:true}))};click('#pack-open');click('#pack-create');assert.match(d.querySelector('#pack-message').textContent,/Enter your name/);click('[data-action="example"]');fill('#pack-role','Sales assistant');fill('#pack-why','I help customers choose products.');fill('#pack-own','I worked on the till.');fill('#pack-ad','<img src=x onerror=alert(1)>');click('#pack-create');assert.match(d.querySelector('#pack-letter').value,/I worked on the till/);assert.equal(d.querySelector('#application img'),null);fill('#pack-letter','My reviewed custom letter');click('[data-ui-language="mk"]');assert.equal(d.querySelector('#pack-letter').value,'My reviewed custom letter');assert.match(d.querySelector('#pack-ad').value,/onerror/);click('#pack-reviewed');assert.equal(d.querySelector('#pack-download').disabled,false);fill('#pack-role','New role');click('#pack-reviewed');assert.equal(d.querySelector('#pack-download').disabled,true);click('[data-action="reset"]');click('#modal-action');click('#pack-open');assert.equal(d.querySelector('#pack-role').value,'');assert.equal(d.querySelector('#pack-letter'),null);dom.window.close()});
test('review requires consent, escapes AI text and applies only approved wording',async()=>{const dom=boot(),w=dom.window,d=w.document;let posted=0;w.AbortSignal=AbortSignal;w.fetch=async(url,options)=>{if(!options?.body)return{ok:true,json:async()=>({available:true})};posted++;assert.equal(JSON.parse(options.body).consent,true);return{ok:true,json:async()=>({overview:'<img src=x onerror=alert(1)>',strengths:[],questions:[],suggestions:[{original:'Plan and deliver digital marketing campaigns.',revised:'Plan digital campaigns and coordinate delivery.',reason:'Clear action.'}]})}};d.querySelector('[data-action="example"]').click();d.querySelector('#review-toggle').click();await new Promise(resolve=>setTimeout(resolve,0));d.querySelector('#review-from').click();assert.equal(d.querySelector('#review-ai').disabled,true);d.querySelector('#review-consent').click();await new Promise(r=>setTimeout(r,0));d.querySelector('#review-ai').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(posted,1);assert.equal(d.querySelector('.ai-results img'),null);assert.match(d.querySelector('#review-edited').value,/Plan and deliver/);d.querySelector('[data-accept="0"]').click();assert.match(d.querySelector('#review-edited').value,/Plan digital campaigns/);assert.match(d.querySelector('#review-source').value,/Plan and deliver/);assert.equal(d.querySelector('#review-pdf').disabled,true);d.querySelector('#review-checked').click();assert.equal(d.querySelector('#review-pdf').disabled,false);const field=d.querySelector('#review-job');const revised=d.querySelector('#review-edited').value;w.confirm=()=>false;const sourceField=d.querySelector('#review-source'),originalSource=sourceField.value;sourceField.value+=' ';sourceField.dispatchEvent(new w.Event('input'));assert.equal(sourceField.value,originalSource);assert.equal(d.querySelector('#review-edited').value,revised);field.value='Another job';field.dispatchEvent(new w.Event('input'));assert.ok(d.querySelector('.ai-results'));assert.equal(field.value,'');assert.equal(d.querySelector('#review-edited').value,revised);w.confirm=()=>true;field.value='Another job';field.dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('.ai-results'),null);assert.equal(d.querySelector('#review-consent').checked,false);dom.window.close()});

test('review inputs stay locked until an in-flight response is delivered',async()=>{const dom=boot(),w=dom.window,d=w.document;w.AbortSignal=AbortSignal;let finish;w.fetch=async(url)=>{if(url==='/api/review/status')return{ok:true,json:async()=>({available:true})};if(url==='/api/payments/config')return{ok:true,json:async()=>({enabled:false})};return new Promise(resolve=>{finish=()=>resolve({ok:true,json:async()=>({overview:'Complete',strengths:[],questions:[],suggestions:[]})})})};d.querySelector('[data-action="example"]').click();d.querySelector('#review-toggle').click();await new Promise(r=>setTimeout(r,0));d.querySelector('#review-from').click();d.querySelector('#review-consent').click();await new Promise(r=>setTimeout(r,0));d.querySelector('#review-ai').click();for(const id of ['review-source','review-job'])assert.equal(d.getElementById(id).disabled,true);d.querySelector('#pack-open').click();const vacancy=d.getElementById('pack-ad');vacancy.value='Changed during review';vacancy.dispatchEvent(new w.Event('input'));assert.equal(vacancy.value,'');assert.equal(d.getElementById('review-job').value,'');finish();await new Promise(r=>setTimeout(r,0));assert.ok(d.querySelector('.ai-results'));assert.equal(d.getElementById('review-source').disabled,false);dom.window.close()});

test('cover-letter acceptance edits only the letter and source replacement needs confirmation',async()=>{
 const dom=boot(),w=dom.window,d=w.document;w.AbortSignal=AbortSignal;
 const letter='I enjoy helping customers find suitable products.',revision='I enjoy helping customers select suitable products.';
 w.fetch=async(url,options)=>{if(!options?.body)return{ok:true,json:async()=>({available:true})};assert.equal(JSON.parse(options.body).letter,letter);return{ok:true,json:async()=>({overview:'Review',suggestions:[{document:'letter',original:letter,revised:revision,reason:'Clarity'}]})}};
 d.querySelector('[data-action="example"]').click();d.querySelector('#review-toggle').click();await new Promise(r=>setTimeout(r,0));d.querySelector('#review-from').click();const field=d.querySelector('#review-letter');field.value=letter;field.dispatchEvent(new w.Event('input'));d.querySelector('#review-consent').click();await new Promise(r=>setTimeout(r,0));d.querySelector('#review-ai').click();assert.equal(d.querySelector('#review-letter').disabled,true);await new Promise(r=>setTimeout(r,0));
 const cv=d.querySelector('#review-edited').value;d.querySelector('[data-accept="0"]').click();assert.equal(d.querySelector('#review-edited-letter').value,revision);assert.equal(d.querySelector('#review-edited').value,cv);assert.equal(d.querySelector('#review-letter').value,letter);
 w.confirm=()=>false;const original=d.querySelector('#review-letter');original.value='Replacement';original.dispatchEvent(new w.Event('input'));assert.equal(original.value,letter);assert.equal(d.querySelector('#review-edited-letter').value,revision);dom.window.close();
});

test('step changes focus and scroll the new heading; missing name stays visibly explained',()=>{
 const dom=boot(),w=dom.window,d=w.document;
 d.querySelector('[data-step="1"]').click();assert.equal(d.activeElement.id,'step-heading');assert.equal(w.lastScroll.id,'step-heading');assert.equal(w.lastScroll.options.block,'start');
 d.querySelector('[data-action="export"]').click();assert.equal(d.activeElement.id,'name');assert.equal(d.querySelector('#name-error').hidden,false);assert.match(d.querySelector('#name-error').textContent,/Enter your full name/);dom.window.close();
});
test('email and reversed-date warnings are nonblocking and clear when corrected',()=>{
 const dom=boot(),w=dom.window,d=w.document;const fill=(id,value)=>{const el=d.getElementById(id);el.value=value;el.dispatchEvent(new w.Event('input'))};
 fill('name','Candidate');fill('email','marko@');assert.equal(d.getElementById('email-warning').hidden,false);d.querySelector('[data-action="export"]').click();assert.match(d.querySelector('#modal').textContent,/Check the email/);d.querySelector('[data-close]').click();
 fill('email','marko@example.com');assert.equal(d.getElementById('email-warning').hidden,true);
 d.querySelector('[data-step="1"]').click();d.querySelector('[data-add="experience"]').click();fill('experience-0-start','2022');fill('experience-0-end','2019');assert.equal(d.getElementById('experience-0-end-warning').hidden,false);fill('experience-0-end','Present');assert.equal(d.getElementById('experience-0-end-warning').hidden,true);dom.window.close();
});
test('shared vacancy syncs both ways and prevents overwriting a finished or in-flight review',async()=>{
 const dom=boot(),w=dom.window,d=w.document;const fill=(id,value)=>{const el=d.getElementById(id);el.value=value;el.dispatchEvent(new w.Event('input'))};w.fetch=async()=>({ok:true,json:async()=>({available:false})});
 d.querySelector('#pack-open').click();fill('pack-ad','Friendly service');d.querySelector('#review-toggle').click();await new Promise(r=>setTimeout(r,0));assert.equal(d.getElementById('review-job').value,'Friendly service');assert.equal(d.getElementById('review-consent').disabled,true);
 fill('review-job','Accurate cash handling');assert.equal(d.getElementById('pack-ad').value,'Accurate cash handling');
 fill('review-source','Customer service assistant with experience helping customers choose products and handling checkout transactions.');d.querySelector('#review-local').click();w.confirm=()=>false;fill('pack-ad','Replacement');assert.equal(d.getElementById('pack-ad').value,'Accurate cash handling');assert.ok(d.getElementById('review-edited'));
 w.confirm=()=>true;fill('pack-ad','New vacancy');assert.equal(d.getElementById('review-job').value,'New vacancy');assert.equal(d.getElementById('review-edited'),null);dom.window.close();
});
test('sample is marked on the paper and requirement changes invalidate a reviewed letter',()=>{
 const dom=boot(),w=dom.window,d=w.document;const fill=(id,value)=>{const el=d.getElementById(id);el.value=value;el.dispatchEvent(new w.Event('input'))};assert.match(d.querySelector('.paper .sample-badge').textContent,/Example/);
 d.querySelector('[data-action="example"]').click();assert.equal(d.querySelector('.sample-badge'),null);d.querySelector('#pack-open').click();fill('pack-role','Assistant');fill('pack-requirement','Friendly service');fill('pack-why','I enjoy helping people.');fill('pack-own','Served customers.\nTrained colleagues.');d.querySelector('#pack-create').click();assert.match(d.getElementById('pack-letter').value,/Friendly service/);assert.match(d.getElementById('pack-letter').value,/• Trained colleagues/);
 assert.ok(d.querySelector('#pack-reviewed').labels.length);assert.ok(d.querySelector('[data-evidence]').labels.length);d.querySelector('#pack-reviewed').click();assert.equal(d.getElementById('pack-download').disabled,false);fill('pack-requirement','Cash handling');d.querySelector('#pack-reviewed').click();assert.equal(d.getElementById('pack-download').disabled,true);dom.window.close();
});
