import {mkdir,writeFile} from 'node:fs/promises';
import {resourceGuides} from './mk-resources.mjs';

export const guides=[
 {slug:'cv-obrazec',title:'CV образец на македонски: пример и бесплатен PDF',description:'Погледни целосен измислен пример за CV на македонски. Избери еден од 8 шаблони, внеси свои податоци и преземи PDF бесплатно.',body:`
<p>CV образецот ти дава структура, но содржината треба да биде твоја. Во CV Hapi можеш да избереш еден од осумте шаблони, да ги пополниш секциите и бесплатно да преземеш PDF. Не е потребна регистрација.</p>
<h2>Пример за CV на македонски</h2><p>Следниот пример е целосно измислен. Прилагоди ја структурата, а не туѓото искуство. Контактите се оставени како полиња за пополнување.</p>
<section class="cv-example" aria-label="Измислен пример за CV"><h3>Марија Петровска</h3><p>Административна асистентка · Скопје<br>Телефон: [твој број] · Е-пошта: [твоја е-пошта]</p><h4>Краток профил</h4><p>Административна асистентка со искуство во организација на документи, комуникација со клиенти и закажување состаноци. Користам табели за следење на обврските и внимавам на точноста на податоците.</p><h4>Работно искуство</h4><p><strong>Административна асистентка — Пример ДОО, Скопје</strong><br>Март 2023 – септември 2026</p><ul><li>Ги средував влезните документи и ја ажурирав електронската евиденција.</li><li>Одговарав на прашања од клиенти по телефон и е-пошта.</li><li>Закажував состаноци и го подготвував потребниот материјал.</li></ul><h4>Образование</h4><p>Средно економско образование — Пример училиште, Скопје<br>2018 – 2022</p><h4>Вештини</h4><ul><li>Организација на документи и рокови</li><li>Работа со табели и обработка на текст</li><li>Писмена и телефонска комуникација</li></ul><h4>Јазици</h4><p>Македонски — мајчин јазик<br>Англиски — средно ниво</p></section>
<h2>Како да го пополниш образецот</h2><ol><li>Избери дизајн што лесно се чита. За поформална пријава, започни со едноставен шаблон.</li><li>Внеси ги твоите контакти, образование и вистинско искуство.</li><li>Опиши конкретни задачи. Додај бројки само ако можеш да ги потврдиш.</li><li>Провери го прегледот и преземи PDF. Отвори го преземениот документ пред испраќање.</li></ol>
<h2>PDF, Word или Europass?</h2><p>CV Hapi создава PDF, а не Word образец. PDF го задржува изгледот при отворање на друг уред. Ако работодавачот бара Word или Europass, следи го тоа барање. Нашите осум шаблони се сопствени дизајни и не се официјален Europass формат.</p>
<h2>Што е бесплатно?</h2><p>Изработката, уредувањето и преземањето PDF се бесплатни. За постоечко CV, AI-проверката е по избор: три проверки за 150 денари еднократно, без претплата. Можеш да продолжиш со бесплатно уредување.</p>`},
 {slug:'kako-da-napisam-cv',title:'Како да напишеш CV на македонски',description:'Чекори за јасно CV на македонски: контакти, профил, искуство, образование и вештини. Со примери и проверка пред испраќање.',body:`
<p>Доброто CV му помага на работодавачот брзо да разбере што знаеш и што си работел/а. Почни со огласот: кои задачи и вештини се важни за конкретното работно место? Избери вистински примери од твоето искуство што одговараат на тие барања.</p>
<h2>1. Внеси контакти што можат да се користат</h2><p>Напиши име и презиме, телефон, е-пошта и град. Провери ги контактите буква по буква. Додај портфолио ако е релевантно. Не внесувај матичен број, број на лична карта или други чувствителни податоци.</p>
<h2>2. Напиши краток профил</h2><p>Во две или три реченици кажи какво искуство имаш, што знаеш и за каква улога се пријавуваш. Избегнувај општи изјави без пример.</p><blockquote>Измислен пример: „Имам искуство во работа со клиенти и водење евиденција. Организирам документи и ги следам договорените рокови. Барам административна улога во која ќе ги користам овие вештини.“</blockquote>
<h2>3. Опиши го работното искуство</h2><p>Почни со најновата работа. За секој запис внеси позиција, работодавач и период. Под нив додај кратки описи на задачите. Разликата меѓу нејасен и корисен опис е конкретноста, а не звучните зборови.</p><div class="comparison"><p><strong>Нејасно:</strong> „Работа со документи.“</p><p><strong>Поконкретно:</strong> „Ги средував влезните документи и ја ажурирав електронската евиденција.“</p></div><p>Ова е пример за формулација, не факт што треба да го преземеш. Наведи резултат или бројка само ако навистина се однесува на твојата работа.</p>
<h2>4. Додај образование и релевантни курсеви</h2><p>Внеси училиште или факултет, насока и период. Ако сè уште студираш, кажи го тоа. Ако курсот е важен за огласот, наведи што си научил/а и кога си го завршил/а. Не наведувај диплома што не си ја стекнал/а.</p>
<h2>5. Избери вештини и јазици</h2><p>Наведи алатки и задачи што можеш самостојно да ги користиш или извршуваш. За јазиците внеси го вистинското ниво. Подготви пример од работа, проект или образование со кој можеш да ја објасниш секоја важна вештина.</p>
<h2>Проверка пред испраќање</h2><ul><li>Контактите и датумите се точни.</li><li>Секоја наведена квалификација е вистинска.</li><li>Најважното искуство за огласот лесно се забележува.</li><li>Текстот е читлив, без правописни грешки.</li><li>PDF се отвора и македонските букви се прикажуваат правилно.</li></ul><p>На почеток на кариерата, една страница често е доволна. Додај втора ако имаш релевантно искуство. Следи ги барањата за формат, фотографија и јазик наведени во огласот.</p>`},
 {slug:'cv-bez-rabotno-iskustvo',title:'CV без работно искуство: пример за прва работа',description:'Напиши CV за прва работа со образование, проекти, практика и волонтирање. Измислен пример на македонски, без измислени квалификации.',body:`
<p>Не мора да имаш претходно вработување за да напишеш корисно CV. Образованието, студентските проекти, практиката и волонтирањето можат да покажат што знаеш. Важно е јасно да објасниш што навистина си направил/а.</p>
<h2>Како да ги подредиш секциите</h2><ol><li>Име, телефон, е-пошта и град</li><li>Краток профил за улогата што ја бараш</li><li>Образование и релевантни предмети</li><li>Проекти, практика или волонтирање</li><li>Вештини и јазици</li></ol><p>Ако немаш работно искуство, не измислувај работодавач. Проектите опиши ги како проекти, а волонтирањето како волонтирање.</p>
<h2>Измислен пример за почетничко CV</h2><section class="cv-example" aria-label="Измислен пример за прва работа"><h3>Давид Стојановски</h3><p>Пријава за почетна административна позиција · Битола<br>Телефон: [твој број] · Е-пошта: [твоја е-пошта]</p><h4>Краток профил</h4><p>Завршив средно економско образование. Во училишни проекти работев со табели, подготовка на документи и презентации. Барам прва работа во која ќе учам административни задачи и комуникација со клиенти.</p><h4>Образование</h4><p>Средно економско образование — Пример училиште, Битола<br>2022 – 2026</p><h4>Училишен проект</h4><p><strong>Евиденција на трошоци за училишен настан — 2026</strong></p><ul><li>Во група подготвивме табела со планирани и реализирани трошоци.</li><li>Ги проверував внесените суми и ги средував податоците за презентацијата.</li></ul><h4>Волонтирање</h4><p><strong>Помош при локален настан — 2025</strong></p><ul><li>Ги насочував посетителите и помагав при подготовка на материјалите.</li></ul><h4>Вештини и јазици</h4><p>Основна работа со табели, обработка на текст и презентации.<br>Македонски — мајчин јазик. Англиски — основно ниво.</p></section>
<h2>Претвори го твоето искуство во конкретен опис</h2><p>Избери задача од училиште, курс или волонтирање. Запиши што требало да се направи, што направи ти и што научи. „Подготвив презентација и ги објаснив резултатите пред класот“ кажува повеќе од „комуникативна личност“, ако навистина си го направил/а тоа.</p>
<h2>Ако немаш проект или практика</h2><p>Фокусирај се на образованието и вештините што можеш да ги покажеш. Не ги препишувај проектите од примерот. Можеш да подготвиш мал сопствен проект релевантен за улогата, а потоа да го наведеш како личен проект со вистински датум и опис.</p>
<h2>Пред да го испратиш CV-то</h2><p>Провери ги контактите, датумите и правописот. Прочитај го огласот повторно и отстрани нерелевантни детали. Не ветувај ниво на вештина што сè уште го немаш. Бесплатниот уредувач во CV Hapi ти овозможува да направиш PDF; AI-проверката е незадолжителна и не гарантира вработување.</p>`}
];
guides.push(...resourceGuides);
for(const guide of guides){
 guide.published=resourceGuides.includes(guide)?'2026-10-06':'2026-10-05';
 guide.modified='2026-10-06';
 guide.kind ||= 'Article';
}
guides.find(g=>g.slug==='cv-obrazec').body+=`<h2>Преземи го примерот или празна структура</h2><p><a href="/downloads/cv-primer-classic-mk.pdf" download>Измисленото CV на Марија во PDF</a> · <a href="/downloads/cv-obrazec-mk.txt" download>Празен образец во TXT</a>. За споредба на дизајни, отвори ги <a href="/mk/cv-sabloni/">осумте шаблони со PDF примери</a>. Примерот не е лична пријава: замени ги сите факти со свои.</p>`;
guides.find(g=>g.slug==='cv-bez-rabotno-iskustvo').body+=`<h2>Пример во PDF и следниот чекор</h2><p><a href="/downloads/cv-prva-rabota-mk.pdf" download>Преземи го измисленото CV на Давид во PDF</a>. Пред да ја испратиш сопствената пријава, помини ја <a href="/mk/proverka-na-cv/">бесплатната листа за проверка</a>. Ако се бара писмо, погледни го <a href="/mk/motivacisko-pismo/">образецот за мотивациско писмо</a>.</p>`;
guides.find(g=>g.slug==='kako-da-napisam-cv').body+=`<h2>Подготви го документот за испраќање</h2><p>Избери <a href="/mk/cv-sabloni/">читлив CV шаблон</a> и отвори го преземениот PDF. Користи ја <a href="/mk/proverka-na-cv/">листата за проверка</a> за да ги провериш контактите, фактите и форматот. Ако огласот бара писмо, подготви <a href="/mk/motivacisko-pismo/">мотивациско писмо за конкретната позиција</a>.</p><h2>Официјални дополнителни насоки</h2><p><a href="https://av.gov.mk/makedonski-ns_article-rabotna-biografija-cv.nspx">Агенција за вработување: работна биографија</a> · <a href="https://europass.europa.eu/mk/create-europass-cv">Europass: креирање CV</a>. CV Hapi не е поврзан со овие институции.</p>`;

const escape=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function writeGuides(origin,live){
 for(const guide of guides){
  const route=`mk/${guide.slug}/`,url=origin+'/'+route,title=guide.title+' | CV Hapi';
  const related=guides.filter(x=>x!==guide&&x.slug!=='soveti-za-cv').map(x=>`<li><a href="/mk/${x.slug}/">${escape(x.title)}</a></li>`).join('');
  const image=origin+'/images/cv-career-hero-1000.webp';
  const page={'@type':guide.kind,'@id':url+'#page',url,name:guide.title,headline:guide.title,description:guide.description,inLanguage:'mk',mainEntityOfPage:url,datePublished:guide.published,dateModified:guide.modified,author:{'@type':'Organization',name:'CV Hapi',url:origin+'/mk/'},image};
  const structured={'@context':'https://schema.org','@graph':[page,{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'CV Hapi',item:origin+'/mk/'},{'@type':'ListItem',position:2,name:'Совети за CV',item:origin+'/mk/soveti-za-cv/'},...(guide.slug==='soveti-za-cv'?[]:[{'@type':'ListItem',position:3,name:guide.title,item:url}])]}]};
  const html=`<!doctype html><html lang="mk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(guide.description)}"><meta name="robots" content="${live?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="${url}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/guides.css"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(guide.description)}"><meta property="og:url" content="${url}"><meta property="og:type" content="article"><meta property="og:locale" content="mk_MK"><script type="application/ld+json">${JSON.stringify(structured)}</script></head><body><a class="skip" href="#article">До содржината</a><header><a class="brand" href="/mk/" aria-label="CV Hapi">CV<span>hapi</span></a><nav aria-label="Главна навигација"><a href="/mk/">Бесплатен уредувач за CV</a><a href="/mk/review/">Проверка на CV</a></nav></header><main id="article"><nav class="breadcrumb" aria-label="Патека"><a href="/mk/">CV Hapi</a><span>Совети за CV</span></nav><article><p class="eyebrow">СОВЕТИ ЗА CV</p><h1>${escape(guide.title)}</h1>${guide.body}</article><aside class="cta"><h2>Направи го твоето CV</h2><p>8 шаблони. Бесплатно уредување и PDF. Без регистрација.</p><a class="button" href="/mk/">Започни со бесплатно CV</a><p class="paid-note">AI-проверката е по избор: 3 проверки за 150 денари еднократно. Без претплата.</p></aside><nav class="related" aria-label="Поврзани совети"><h2>Прочитај и</h2><ul>${related}</ul></nav></main><footer><p>CV Hapi · <a href="/mk/">CV на македонски</a> · <a href="mailto:support@cvhapi.com">support@cvhapi.com</a></p></footer></body></html>`;
  const shareText=encodeURIComponent(`${guide.title} — CV Hapi\n${url}`);
  const sharing=`<section class="sharing" aria-label="Споделување"><h2>Сподели корисен водич</h2><p>Сподели ја оваа страница со некој што подготвува пријава. Линкот не содржи твои лични податоци.</p><div><a href="https://wa.me/?text=${shareText}" rel="noopener noreferrer" target="_blank">WhatsApp</a><a href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}" rel="noopener noreferrer" target="_blank">Facebook</a><a href="mailto:?subject=${encodeURIComponent(guide.title)}&body=${shareText}">Е-пошта</a></div></section>`;
  const output=html.replace('</head>',`<meta property="og:site_name" content="CV Hapi"><meta property="og:image" content="${image}"><meta property="og:image:alt" content="CV Hapi — бесплатен уредувач за CV"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(guide.description)}"><meta name="twitter:image" content="${image}"></head>`)
   .replace('<span>Совети за CV</span>','<a href="/mk/soveti-za-cv/">Совети за CV</a>')
   .replace('<a href="/mk/review/">Проверка на CV</a>','<a href="/mk/soveti-za-cv/">Примери и совети</a><a href="/mk/review/">Увези CV</a>')
   .replace('</h1>',`</h1><p class="byline">Подготвено од CV Hapi · Ажурирано на <time datetime="${guide.modified}">6 октомври 2026</time></p>`)
   .replace('</main>',sharing+'</main>');
  await mkdir('dist/client/'+route,{recursive:true});await writeFile('dist/client/'+route+'index.html',output);
 }
}
