import {escapeHtml as e} from './model.js';
import {evidenceOptions,draftLetter,applicationDocument} from './application.js';
import {track} from './telemetry.js';

const copy={
 en:{title:'Apply for a specific job.',intro:'Start with a free CV. Then connect your experience to the vacancy and prepare a cover letter.',free:'Edit my free CV',open:'Prepare an application',price:'Free during the pilot. No card. No subscription.',status:'Guided cover-letter template · No automatic translation',heading:'Your application workspace',hint:'Paste the vacancy for reference. Choose real examples, explain why they matter, and review the result. This pilot uses a fixed letter template, not AI.',role:'Job you are applying for',company:'Company (optional)',ad:'Job advertisement (optional)',adHint:'Kept in this tab only. Read it alongside your experience; no automatic scoring or analysis.',requirement:'What does the employer need most?',why:'Why are you a good fit? Use your own words.',evidence:'Choose up to 3 examples from your CV',none:'Add descriptions under Experience or Education in your CV first, or write an example below.',own:'Another true example (optional)',summary:'CV profile for this application',language:'Document headings and letter template',languageHint:'Your own words are not translated. Write them in the language you will use to apply.',create:'Create my draft',review:'Review your application',letter:'Cover letter — edit before downloading',check:'I have checked the facts, language, contact details and the vacancy requirements.',download:'Download CV + cover letter',note:'One PDF: your CV first, then the letter. All existing CV entries are kept. For separate CV uploads, use Download PDF in the header.',missing:'Enter your name in the CV, a job title, why you fit, and at least one real example.',tooMany:'Choose no more than 3 examples in total.',confirm:'Creating a new draft replaces edits to the letter. Continue?',error:'Could not create the PDF. Your draft is still here; please try again.',success:'Application PDF is ready.',survey:'Would a reviewed application be worth NOK 10?',surveyText:'This is a preference question, not a purchase. The current pilot is free.',yes:'Yes, I would consider it',no:'I would use the free version',thanks:'Thanks — no payment has been taken.',reference:'Vacancy notes',editCv:'Back to my CV',draftHint:'Draft and vacancy text stay in this tab. Download before closing. Changing CV details requires a new review.'},
 mk:{title:'Аплицирај за конкретна работа.',intro:'Почни со бесплатно CV. Поврзи го твоето искуство со огласот и подготви мотивациско писмо.',free:'Уреди го бесплатното CV',open:'Подготви пријава',price:'Бесплатно во пилот-фазата. Без картичка и без претплата.',status:'Воден шаблон за писмо · Без автоматски превод',heading:'Твојата пријава за работа',hint:'Залепи го огласот како потсетник. Избери вистински примери, објасни зошто се релевантни и провери го резултатот. Овој пилот користи фиксен шаблон за писмо, не AI.',role:'Работна позиција за која аплицираш',company:'Компанија (незадолжително)',ad:'Оглас за работа (незадолжително)',adHint:'Останува само во ова јазиче. Спореди го со искуството; нема автоматско оценување или анализа.',requirement:'Што му е најважно на работодавецот?',why:'Зошто одговараш за позицијата? Напиши со свои зборови.',evidence:'Избери до 3 примери од твоето CV',none:'Прво додај опис во Искуство или Образование, или напиши пример подолу.',own:'Друг вистински пример (незадолжително)',summary:'Краток профил за оваа пријава',language:'Јазик на насловите и шаблонот за писмо',languageHint:'Твојот текст не се преведува. Пишувај на јазикот на пријавата.',create:'Создај нацрт',review:'Провери ја пријавата',letter:'Мотивациско писмо — уреди пред преземање',check:'Ги проверив фактите, јазикот, контактите и барањата во огласот.',download:'Преземи CV + писмо',note:'Еден PDF: прво CV, потоа писмото. Сите записи од CV-то се задржуваат. За посебно CV, користи „Преземи PDF“ во заглавието.',missing:'Внеси име во CV-то, работна позиција, зошто одговараш и барем еден вистински пример.',tooMany:'Избери најмногу 3 примери вкупно.',confirm:'Новиот нацрт ќе ги замени измените во писмото. Продолжи?',error:'PDF не можеше да се создаде. Нацртот е тука; обиди се повторно.',success:'PDF-пријавата е подготвена.',survey:'Дали проверена пријава вреди 10 NOK?',surveyText:'Ова е прашање за интерес, не купување. Тековниот пилот е бесплатен.',yes:'Да, би размислил/а',no:'Би ја користел/а бесплатната верзија',thanks:'Благодариме — не е извршена наплата.',reference:'Белешки за огласот',editCv:'Назад кон CV-то',draftHint:'Нацртот и огласот остануваат во ова јазиче. Преземи пред затворање. Измена на CV-то бара нова проверка.'}
};
let pack=empty(),open=false,reviewed=false,busy=false,answer=null,draftInputs=null;
const inputs=(cv)=>JSON.stringify([cv.name,pack.role,pack.company,pack.why,pack.own,pack.selected,pack.language]);
function empty(){return{role:'',company:'',ad:'',requirement:'',why:'',own:'',summary:'',language:'en',selected:[],letter:'',initialized:false}}
export function resetApplication(){pack=empty();open=false;reviewed=false;answer=null;draftInputs=null}
export function mountApplication({ui,getCV,onEditCV}){
 reviewed=false;
 const root=document.querySelector('#application');if(!root)return;
 const t=copy[ui];const cv=getCV();
 if(!pack.initialized){pack.language=ui;pack.summary=cv.summary;}
 const input=(key,label,max=200,area=false)=>`<label for="pack-${key}">${e(label)}<${area?'textarea':'input'} id="pack-${key}" data-pack="${key}" maxlength="${max}" ${area?'rows="4"':`value="${e(pack[key])}"`}>${area?e(pack[key])+'</textarea>':''}</label>`;
 const options=evidenceOptions(cv);
 // Keep selections only while the underlying evidence still exists unchanged.
 pack.selected=pack.selected.filter(v=>options.some(x=>x.text===v));
 root.innerHTML=`<div class="offer"><div><p class="eyebrow">CV + ${ui==='mk'?'МОТИВАЦИСКО ПИСМО':'COVER LETTER'}</p><h1>${t.title}</h1><p>${t.intro}</p><p class="offer-price">${t.price}</p></div><div class="offer-actions"><button class="primary" id="pack-open" aria-expanded="${open}" aria-controls="pack-panel">${t.open} →</button><button class="text-button" id="pack-cv">${t.free}</button></div></div>${open?`<section id="pack-panel" class="pack-panel" aria-labelledby="pack-title"><div class="pack-heading"><div><p class="pilot-label">${t.status}</p><h2 id="pack-title" tabindex="-1">${t.heading}</h2></div><button class="secondary" id="pack-back">${t.editCv}</button></div><p>${t.hint}</p><div class="pack-grid"><div>${input('role',t.role)}${input('company',t.company)}${input('ad',t.ad,12000,true)}<p class="hint">${t.adHint}</p>${input('requirement',t.requirement,1500,true)}${input('why',t.why,2500,true)}</div><div><fieldset class="evidence"><legend>${t.evidence}</legend>${options.length?options.map((x,i)=>`<label><input type="checkbox" data-evidence="${i}" ${pack.selected.includes(x.text)?'checked':''}><span><strong>${e(x.label)}</strong><span>${e(x.text)}</span></span></label>`).join(''):`<p class="hint">${t.none}</p>`}</fieldset>${input('own',t.own,2000,true)}${input('summary',t.summary,2200,true)}<label for="pack-language">${t.language}<select id="pack-language"><option value="en" ${pack.language==='en'?'selected':''}>English</option><option value="mk" ${pack.language==='mk'?'selected':''}>Македонски</option></select></label><p class="hint">${t.languageHint}</p><button class="primary" id="pack-create">${t.create} →</button></div></div><p id="pack-message" role="status" aria-live="polite"></p>${pack.letter?`<div class="pack-review"><h3>${t.review}</h3>${input('letter',t.letter,12000,true)}<p>${t.note}</p><label class="review-check"><input type="checkbox" id="pack-reviewed">${t.check}</label><button class="primary" id="pack-download" disabled>${t.download} ↓</button><p class="hint">${t.draftHint}</p></div><div class="pack-survey"><h3>${t.survey}</h3><p>${t.surveyText}</p>${answer===null?`<button class="secondary" data-answer="yes">${t.yes}</button> <button class="text-button" data-answer="no">${t.no}</button>`:`<p role="status">${t.thanks}</p>`}</div>`:''}</section>`:''}`;
 const q=s=>root.querySelector(s);const message=text=>{q('#pack-message').textContent=text};
 q('#pack-cv').onclick=onEditCV;
 q('#pack-open').onclick=()=>{open=!open;if(open){pack.initialized=true;if(!pack.summary)pack.summary=getCV().summary;track('application_started')}mountApplication({ui,getCV,onEditCV});if(open)q('#pack-title').focus()};
 if(!open)return;
 q('#pack-back').onclick=onEditCV;
 function invalidate(){reviewed=false;const check=q('#pack-reviewed');if(check)check.checked=false;const download=q('#pack-download');if(download)download.disabled=true;}
 root.querySelectorAll('[data-pack]').forEach(el=>el.oninput=()=>{pack[el.dataset.pack]=el.value;pack.initialized=true;invalidate()});
 root.querySelectorAll('[data-evidence]').forEach(el=>el.onchange=()=>{const value=options[Number(el.dataset.evidence)].text;pack.selected=pack.selected.filter(x=>x!==value);if(el.checked)pack.selected.push(value);invalidate()});
 q('#pack-language').onchange=event=>{pack.language=event.target.value;invalidate()};
 q('#pack-create').onclick=()=>{
   const examples=[...pack.selected,...(pack.own.trim()?[pack.own]:[])];
   if(!getCV().name.trim()||!pack.role.trim()||!pack.why.trim()||!examples.length){message(t.missing);track('application_validation_error');return}
   if(examples.length>3){message(t.tooMany);return}
   if(pack.letter&&!window.confirm(t.confirm))return;
   pack.letter=draftLetter({...pack,name:getCV().name,evidence:examples});draftInputs=inputs(getCV());reviewed=false;track('application_drafted');mountApplication({ui,getCV,onEditCV});q('#pack-letter').focus();
 };
 const check=q('#pack-reviewed');if(check)check.onchange=()=>{const stale=draftInputs!==inputs(getCV());reviewed=check.checked&&!stale;q('#pack-download').disabled=!reviewed||busy;if(stale)message(ui==='mk'?'Податоците се изменети. Создај нов нацрт пред преземање.':'Your details changed. Create a new draft before downloading.')};
 const download=q('#pack-download');if(download)download.onclick=async()=>{
   if(!reviewed||busy)return;busy=true;download.disabled=true;
   try{const {downloadDocument}=await import('./pdf.js');await downloadDocument(applicationDocument(getCV(),pack),'Application.pdf');message(t.success);track('application_pdf_generated')}
   catch{message(t.error);track('application_pdf_error')}
   finally{busy=false;download.disabled=!reviewed}
 };
 root.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>{answer=button.dataset.answer;track(answer==='yes'?'package_interest_yes':'package_interest_no');mountApplication({ui,getCV,onEditCV})});
}
