export const STORAGE_KEY='cekor.cv.v1';
export const blank=()=>({name:'',role:'',email:'',phone:'',city:'',website:'',summary:'',experience:[],education:[],skills:'',languages:'',template:'modern',accent:'#234bff',language:'mk'});
export const example={name:'Ана Стојановска',role:'Маркетинг специјалист',email:'ana@example.com',phone:'+389 70 123 456',city:'Скопје',website:'',summary:'Креативна маркетинг специјалистка со искуство во дигитални кампањи, создавање содржини и комуникација со клиенти.',experience:[{title:'Маркетинг специјалист',organization:'Студио Север',start:'2022',end:'денес',description:'Планирање и спроведување дигитални кампањи.\nКоординација на содржини и соработка со креативниот тим.'}],education:[{title:'Дипломиран економист',organization:'Универзитет „Св. Кирил и Методиј“',start:'2018',end:'2022',description:'Економски факултет, Скопје'}],skills:'Дигитален маркетинг, Комуникација, Excel, Google Analytics',languages:'Македонски — мајчин јазик\nАнглиски — Б2'};
export const limits={name:100,role:120,email:150,phone:50,city:120,website:200,summary:2200,skills:1800,languages:1200,title:150,organization:180,start:40,end:40,description:3500};
export const exampleEnglish={name:'Ana Stojanovska',role:'Marketing Specialist',email:'ana@example.com',phone:'+389 70 123 456',city:'Skopje',website:'',summary:'Creative marketing specialist with experience in digital campaigns, content creation and client communication.',experience:[{title:'Marketing Specialist',organization:'North Studio',start:'2022',end:'Present',description:'Plan and deliver digital marketing campaigns.\nCoordinate content and collaborate with the creative team.'}],education:[{title:'Bachelor of Economics',organization:'Ss. Cyril and Methodius University',start:'2018',end:'2022',description:'Faculty of Economics, Skopje'}],skills:'Digital marketing, Communication, Excel, Google Analytics',languages:'Macedonian — Native\nEnglish — B2'};
export function normalize(raw){const d=blank();if(!raw||typeof raw!=='object')return d;for(const k of ['name','role','email','phone','city','website','summary','skills','languages'])if(typeof raw[k]==='string')d[k]=raw[k].slice(0,limits[k]);for(const k of ['experience','education'])d[k]=Array.isArray(raw[k])?raw[k].slice(0,20).filter(x=>x&&typeof x==='object').map(x=>Object.fromEntries(['title','organization','start','end','description'].map(f=>[f,typeof x[f]==='string'?x[f].slice(0,limits[f]):'']))):[];if(['modern','classic','compact'].includes(raw.template))d.template=raw.template;if(['#234bff','#176554','#343d50','#9a3b26'].includes(raw.accent))d.accent=raw.accent;if(['mk','en'].includes(raw.language))d.language=raw.language;return d}
export const hasContent=d=>['name','role','email','phone','city','website','summary','skills','languages'].some(k=>d[k].trim())||[...d.experience,...d.education].some(x=>Object.values(x).some(v=>v.trim()));
export const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const headings={mk:{profile:'ПРОФИЛ',experience:'РАБОТНО ИСКУСТВО',education:'ОБРАЗОВАНИЕ',skills:'ВЕШТИНИ',languages:'ЈАЗИЦИ'},en:{profile:'PROFILE',experience:'WORK EXPERIENCE',education:'EDUCATION',skills:'SKILLS',languages:'LANGUAGES'}};
export function documentDefinition(input){const d=normalize(input),h=headings[d.language],compact=d.template==='compact';const content=[{text:d.role,style:'role'},{text:d.name,style:'name'},{text:[d.city,d.email,d.phone,d.website].filter(Boolean).join('  •  '),style:'contact'},{canvas:[{type:'line',x1:0,y1:0,x2:499,y2:0,lineWidth:d.template==='classic'?1:2,lineColor:d.accent}],margin:[0,16,0,4]}];function section(title,body){if(body.length)content.push({text:title,style:'heading'},...body)}if(d.summary.trim())section(h.profile,[{text:d.summary}]);for(const k of ['experience','education'])section(h[k],d[k].filter(x=>Object.values(x).some(v=>v.trim())).flatMap(x=>[{text:x.title||x.organization,bold:true,margin:[0,0,0,3]},{text:[x.title?x.organization:'',[x.start,x.end].filter(Boolean).join(' – ')].filter(Boolean).join(' | '),color:'#657084',margin:[0,0,0,5]},...(x.description?[{text:x.description,margin:[0,0,0,12]}]:[])]));if(d.skills.trim())section(h.skills,[{text:d.skills}]);if(d.languages.trim())section(h.languages,[{text:d.languages}]);return{pageSize:'A4',pageMargins:[48,42,48,42],info:{title:`CV — ${d.name}`,author:d.name,creator:'CV Hapi'},defaultStyle:{font:'Roboto',fontSize:compact?10:11,lineHeight:1.25,color:'#202735'},content,styles:{role:{fontSize:10,bold:true,color:d.accent,characterSpacing:1},name:{fontSize:d.template==='classic'?29:34,bold:true,margin:[0,8,0,12]},contact:{fontSize:9,color:'#657084'},heading:{fontSize:10,bold:true,color:d.accent,characterSpacing:1,margin:[0,compact?15:22,0,8]}},footer:(n,total)=>({text:`${n} / ${total}`,alignment:'right',fontSize:8,color:'#657084',margin:[48,10,48,0]}),pageBreakBefore:(node,following)=>node.style==='heading'&&following.length===0}}
