const labels={en:{buy:'Test checkout — €2 once',check:'Check payment',note:'TEST MODE: one AI review. Use a Stripe test card only. Keep this CV tab open; checkout opens separately. The CV builder and ordinary PDF remain free. Failed reviews request a refund.',paid:'Test payment verified. You can now run one AI review.',pending:'Payment is not confirmed. Complete checkout, then check again.',used:'This purchase has been used.',refunded:'Refund confirmed.',refund_pending:'Refund requested but not confirmed. Contact the site owner before trying again.',processing:'Your review is processing. Do not pay again.',error:'Payment could not be checked. Your CV is still here. Try checking again.'},mk:{buy:'Тест-плаќање — еднократно 2 €',check:'Провери плаќање',note:'ТЕСТ: една AI-проверка. Користи само тест-картичка од Stripe. Остави го ова јазиче отворено; плаќањето се отвора одделно. Уредувачот и обичниот PDF остануваат бесплатни. Неуспешна проверка бара враќање на уплатата.',paid:'Тест-плаќањето е потврдено. Можеш да направиш една AI-проверка.',pending:'Плаќањето не е потврдено. Заврши го и провери повторно.',used:'Ова купување е искористено.',refunded:'Враќањето на уплатата е потврдено.',refund_pending:'Враќањето е побарано, но не е потврдено. Контактирај го сопственикот пред нов обид.',processing:'Проверката е во тек. Не плаќај повторно.',error:'Не може да се провери плаќањето. Твоето CV е тука. Провери повторно.'}};
export async function mountPayment(root,ui,onState){
 const t=labels[ui],container=document.createElement('div');container.className='payment-choice';container.setAttribute('data-clarity-mask','true');root.append(container);
 try{
  const config=await fetch('/api/payments/config',{cache:'no-store'}).then(r=>r.json());if(!container.isConnected||!config.enabled)return;
  onState(false);
  container.innerHTML=`<p>${t.note}</p><button type="button" class="secondary" data-buy>${t.buy}</button> <button type="button" class="secondary" data-check>${t.check}</button><p role="status"></p>`;
  const message=container.querySelector('[role=status]'),buy=container.querySelector('[data-buy]'),check=container.querySelector('[data-check]');
  const refresh=async()=>{try{const response=await fetch('/api/payments/status',{cache:'no-store'});if(!response.ok)throw Error();const result=await response.json();if(!container.isConnected)return;onState(result.state==='paid');message.textContent=t[result.state]||t.pending;buy.disabled=['paid','processing','refund_pending'].includes(result.state)}catch{message.textContent=t.error}};
  check.onclick=refresh;
  buy.onclick=async()=>{buy.disabled=true;try{const response=await fetch('/api/payments/checkout',{method:'POST'}),result=await response.json();if(!response.ok)throw Error();const url=new URL(result.url);if(url.origin!=='https://checkout.stripe.com')throw Error();const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent=t.buy;container.append(link);link.click();message.textContent=t.pending}catch{message.textContent=t.error}finally{buy.disabled=false}};
  await refresh();
 }catch{/* Payments unavailable: no checkout is advertised. The API fails closed when enabled. */}
}
